.PHONY: android test lint format install help

help:
	@echo "Available commands:"
	@echo "  make android      - Start android app"
	@echo "  make test     - Run tests"
	@echo "  make lint     - Check code style"
	@echo "  make format   - Format code"

install:
	npm install

android:
	npm run android

test:
	npm run test

lint:
	npm run lint

format:
	npm run format
