name: "Setup Node.js"
description: "Install Node.js and cache"
inputs:
  working-directory:
    description: "Directory containing package.json / package-lock.json"
    required: false
    default: "./app"
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "24.14.0"
        cache: "npm"
        cache-dependency-path: "${{ inputs.working-directory }}/package-lock.json"
    - name: Install dependencies
      shell: bash
      run: npm ci --prefix ${{ inputs.working-directory }}
