name: service-assistant-admin

services:
    app:
        build:
            context: .
            args:
                VITE_API_URL: ${VITE_API_URL}
        ports:
            - '127.0.0.1:${PORT}:80'
        restart: unless-stopped
