name: Main workflow

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  client-lint:
    name: Lint (client)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: npm --prefix ./client ci
      - name: Run lint check
        run: npm --prefix ./client run lint

  client-test:
    name: Run tests (client)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: npm --prefix ./client ci
      - name: Run tests
        run: npm --prefix ./client test

  server-lint:
    name: Lint (server)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-poetry
      - name: Install dependencies
        run: poetry --directory ./server install --all-groups
      - name: Run lint check
        run: poetry --directory ./server run ruff check app tests

  server-format-check:
    name: Check formatting (server)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-poetry
      - name: Install dependencies
        run: poetry --directory ./server install --all-groups
      - name: Run format check
        run: poetry --directory ./server run ruff format --check app tests

  server-test:
    name: Run tests (server)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-poetry
      - name: Install dependencies
        run: poetry --directory ./server install --all-groups
      - name: Run tests
        run: poetry --directory ./server run pytest
