name: Main workflow

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  client-lint:
    name: Lint (client)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: npm --prefix ./client ci
      - name: Run lint check
        run: npm --prefix ./client run lint

  client-test:
    name: Run tests (client)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: npm --prefix ./client ci
      - name: Run tests
        run: npm --prefix ./client test

  server-lint:
    name: Lint (server)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: 3.14.3
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.3.2
      - name: Install dependencies
        run: poetry install
      - name: Run lint check
        run: poetry run ruff check app tests

  server-format-check:
    name: Check formatting (server)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: 3.14.3
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.3.2
      - name: Install dependencies
        run: poetry install
      - name: Run format check
        run: poetry run ruff format --check app tests

  server-test:
    name: Run tests (server)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: 3.14.3
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.3.2
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest
        
